routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/register', function () {
    return view('auth.register');
});

Auth::routes();




Route::get('/login', function () {
    return view('pengguna.login');
})->name('login');

Route::post('/postlogin', 'LoginController@postlogin')->name('postlogin');
Route::get('/logout', 'LoginController@logout')->name('logout');



Route::group(['middleware' => ['auth', 'Checklevel:1']], function () {


    Route::get('/Userdata', 'AdminController@user');
    Route::any('/Userdata/data', 'AdminController@data');
    Route::get('/UserAdd', 'AdminController@create');
    Route::any('/Userhapus/{id}', 'AdminController@destroy');

    Route::get('/Kategoridata', 'KategoriController@index');
    Route::get('/Kategori', 'KategoriController@create');
    Route::get('/Kategori/{id}/edit', 'KategoriController@edit');
    Route::put('/Kategori/{id}', 'KategoriController@update');
    Route::any('/Kategoridata/data', 'KategoriController@data');
    Route::any('/Kategorihapus/{id}', 'KategoriController@destroy');

    Route::get('/Barangdata', 'BarangController@index');
    Route::any('/Barangdata/data', 'BarangController@data');
    Route::get('/Barang', 'BarangController@create');
    Route::get('/Barang/{id}/edit', 'BarangController@edit');
    Route::put('/Barang/{id}', 'BarangController@update');
    Route::any('/Baranghapus/{id}', 'BarangController@destroy');

    Route::get('/Supplier', 'SupplierController@index');
    Route::get('/SupplierAdd', 'SupplierController@create');
    Route::get('/Supplier/{id}/edit', 'SupplierController@edit');
    Route::put('/Supplier/{id}', 'SupplierController@update');
    Route::any('/Supplierdata/data', 'SupplierController@data');
    Route::any('/Supplierhapus/{id}', 'SupplierController@destroy');


    Route::get('/Barangmasuk', 'BrgmskController@index');
    Route::get('/BarangmasukAdd', 'BrgmskController@create');
    Route::get('/Barangmasuk/{id}/edit', 'BrgmskController@edit');
    Route::patch('/Barangmasukedit', 'BrgmskController@editjum');
    Route::put('/Barangmasuk/{id}', 'BrgmskController@update');
    Route::put('/Barangmasukhapus/{id}', 'BrgmskController@destroy');
    Route::any('/Barangmasuk/data', 'BrgmskController@data');

    Route::get('/Barangkeluar', 'BrgkelController@index');
    // Route::get('/BarangkeluarAdd', 'BrgkelController@create');
    Route::get('/Barangkeluar/{id}/edit', 'BrgkelController@edit');
    Route::put('/Barangkeluar/{id}', 'BrgkelController@update');
    Route::put('/Barangkeluarhapus/{id}', 'BrgkelController@destroy');
    Route::any('/Barangkeluar/data', 'BrgkelController@data');

    Route::get('/Kasir', 'BrgkelController@kasir');

    Route::get('/Penjual', 'BrgkelController@create');


    Route::group(['prefix' => 'data'], function () {
        Route::resource('Kategori', 'KategoriController');
        Route::resource('Barang', 'BarangController');
        Route::resource('Supplier', 'SupplierController');
        Route::resource('Admin', 'AdminController');
        Route::resource('user', 'UserController'::class);
        Route::resource('Penjual', 'PenjualController');
        Route::resource('Barangmasuk', 'BrgmskController');
        Route::resource('Barangkeluar', 'BrgkelController');
    });
});

Route::group(['middleware' => ['auth', 'Checklevel:1,2']], function () {

    Route::get('/Userdetail/{id}', 'AdminController@show');
    Route::get('/User/{id}/edit', 'AdminController@edit');
    Route::put('/User/{id}', 'AdminController@update');

    Route::get('/UtamaAdmin', 'AdminController@admin');

    Route::get('/Laporan', 'LaporanController@index');
    Route::get('/Laporan/cetak_pdf',  'LaporanController@cetak_pdf')->name('print');

    Route::get('/TglLaporanPen', 'LaporanController@tgllpenjualan');
    Route::get('/LaporanPen/{tgl}', 'LaporanController@lpenjualan');
    Route::get('/LaporanPencetak/{tgl}',  'LaporanController@cetak2_pdf')->name('print');

    Route::get('/Laporanbm', 'LaporanController@lbm');
    Route::get('/Laporanbm/cetak_pdf',  'LaporanController@cetak3_pdf')->name('print');

    Route::group(['prefix' => 'data'], function () {
        Route::resource('Kategori', 'KategoriController');
        Route::resource('Barang', 'BarangController');
        Route::resource('Supplier', 'SupplierController');
        Route::resource('Admin', 'AdminController');
        Route::resource('user', 'UserController'::class);
        Route::resource('Penjual', 'PenjualController');
        Route::resource('Barangmasuk', 'BrgmskController');
        Route::resource('Barangkeluar', 'BrgkelController');
    });
});




// Route::get('/artikel', 'Articlecontroller@index');
// Route::get('/artikel/1', 'Articlecontroller@show');

// Route::get('user/login', 'userController@getLogin')->name('admin.login');
// Route::post('user/login', 'userController@postLogin');

// Route::get('/Admin', 'AdminController');


// Route::get('/PenjualAdd', 'PenjualController@create');
// Route::get('/Penjual/{id}/edit', 'PenjualController@edit');
// Route::put('/Penjual/{id}', 'PenjualController@update');

// Route::get('user/login', 'UserController@getLogin')->name('user.login');
// Route::post('user/login', 'UserController@postLogin');


// Route::get('/home', 'HomeController@index')->name('home');

resources/views/Admin/Penjualan/add_penjualan.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Tambah Penjualan</title>

    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

</head>

<body>
    <form method="POST" action="{{url('data/Penjual')}}">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label for="Id_brg">Pilih Barang:</label>
                <select name="Id_brg" id="Id_brg">
                    <option></option>
                    @foreach ($Join as $join)
                    <option data-barang="{{$join->Id_ktgr}}" data-kat="{{$join->namakat}}"
                        value="{{ $join->Id_barang }}">{{ $join->nama }}</option>
                    @endforeach
                </select>

                <label for="Id_ktgr">Kategori</label>
                <input type="hidden" name="Id_ktgr" readonly />
                <input type="text" name="namakat" readonly />
            
            </br>
                <label for="Id_sup">Pilih Supplier:</label>
                <select name="Id_sup" id="Id_sup">
                    <option></option>
                    @foreach ($Supplier as $sup)
                    <option value="{{ $sup->Id_supplier }}">{{ $sup->Nama }}</option>
                    @endforeach
                </select>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/Penjual/" class="btn btn-info btn-sm">Kembali</a>
            </div>

        </div>
    </form>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script>
    $('#Id_brg').on('change', function(){
  // ambil data dari elemen option yang dipilih
  const barang = $('#Id_brg option:selected').data('barang');
  const namakat = $('#Id_brg option:selected').data('kat');

  // tampilkan data ke element
  $('[name=Id_ktgr]').val(barang);
  $('[name=namakat]').val(namakat);
  
});
</script>

  
</section>
    
</div>

@endsection

resources/views/Admin/Penjualan/datapenjualan.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Data Penjualan</title>
</head>

<body>
    <a href="/PenjualAdd/" class="btn btn-info btn-sm">Tambah Penjualan</a>
    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif
    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Barang</th>
            <th>Kategori</th>
            <th>Supplier</th>
            <th>Image</th>
            <th >Action</th>
        </tr>
        <?php $i = 1; ?>
        @foreach ($Join as $join )
        <tr>

            <td>
                {{ $i++ }}
            </td>
            <td>{{ $join->nama }}</td>
            <td>{{ $join->namakat }}</td>
            <td>{{ $join->Nama }}</td>
            <td><img src="/image/{{ $join->image }}" width='100' height='100'></td>            
            <td>
                <a href="/Penjual/{{$join->Id_penjual}}/edit" class="btn btn">edit</a>
                <form action="{{ route('Penjual.destroy', $join->Id_penjual)}}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-sm btn-danger" onclick="return confirm('Apakah anda yakin ingin menghapus data {{$join->nama}}')">Delete</botton>
                </form>
            </td>
        </tr>
        @endforeach
    </table>

      
</section>
    
</div>

@endsection

resources/views/Admin/Penjualan/editpenjualan.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=, initial-scale=1.0">
    <title>Tambah Penjualan</title>

    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

</head>

<body>
    <form method="POST" action="/Penjual/{{$Penjual->Id_penjual}}">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group">
                <label for="Id_brg">Pilih Barang:</label>
                <select name="Id_brg" id="Id_brg">
                    @foreach ($JoinA as $joina)
                    <option data-barang="{{$joina->Id_ktgr}}" data-kat="{{$joina->namakat}}"
                    value="{{ $joina->Id_penjual }}">--{{ $joina->nama }}--</option>
                    @endforeach
                    @foreach ($JoinB as $joinb)
                    <option data-barang="{{$joinb->Id_ktgr}}" data-kat="{{$joinb->namakat}}"
                    value="{{ $joinb->Id_barang }}">{{ $joinb->nama }}</option>
                    @endforeach
                </select>
                
                <label for="Id_ktgr">Kategori</label>
                <input value="{{ $joina->Id_penjual }}" type="hidden" name="Id_ktgr" readonly />
                <input value="{{ $joina->namakat }}" type="text" name="namakat" readonly />
            
            </br>
                <label for="Id_sup">Pilih Supplier:</label>
                <select name="Id_sup" id="Id_sup">
                    @foreach ($JoinA as $joina)
                    <option value="{{ $joina->Id_penjual }}">--{{ $joina->Nama }}--</option>
                    @endforeach
                    @foreach ($Supplier as $sup)
                    <option value="{{ $sup->Id_supplier }}">{{ $sup->Nama }}</option>
                    @endforeach
                </select>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/Penjual/" class="btn btn-info btn-sm">Kembali</a>
            </div>

        </div>
    </form>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>

<script>
    $('#Id_brg').on('change', function(){
  // ambil data dari elemen option yang dipilih
  const barang = $('#Id_brg option:selected').data('barang');
  const namakat = $('#Id_brg option:selected').data('kat');

  // tampilkan data ke element
  $('[name=Id_ktgr]').val(barang);
  $('[name=namakat]').val(namakat);
  
});
</script>

  
</section>
    
</div>

@endsection