routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/register', function () {
    return view('auth.register');
});

Auth::routes();




Route::get('/login', function () {
    return view('pengguna.login');
})->name('login');

Route::post('/postlogin', 'LoginController@postlogin')->name('postlogin');
Route::get('/logout', 'LoginController@logout')->name('logout');



Route::group(['middleware' => ['auth', 'Checklevel:1']], function () {


    Route::get('/Userdata', 'AdminController@user');
    Route::any('/Userdata/data', 'AdminController@data');
    Route::get('/UserAdd', 'AdminController@create');
    Route::any('/Userhapus/{id}', 'AdminController@destroy');

    Route::get('/Kategoridata', 'KategoriController@index');
    Route::get('/Kategori', 'KategoriController@create');
    Route::get('/Kategori/{id}/edit', 'KategoriController@edit');
    Route::put('/Kategori/{id}', 'KategoriController@update');
    Route::any('/Kategoridata/data', 'KategoriController@data');
    Route::any('/Kategorihapus/{id}', 'KategoriController@destroy');

    Route::get('/Barangdata', 'BarangController@index');
    Route::any('/Barangdata/data', 'BarangController@data');
    Route::get('/Barang', 'BarangController@create');
    Route::get('/Barang/{id}/edit', 'BarangController@edit');
    Route::put('/Barang/{id}', 'BarangController@update');
    Route::any('/Baranghapus/{id}', 'BarangController@destroy');

    Route::get('/Supplier', 'SupplierController@index');
    Route::get('/SupplierAdd', 'SupplierController@create');
    Route::get('/Supplier/{id}/edit', 'SupplierController@edit');
    Route::put('/Supplier/{id}', 'SupplierController@update');
    Route::any('/Supplierdata/data', 'SupplierController@data');
    Route::any('/Supplierhapus/{id}', 'SupplierController@destroy');


    Route::get('/Barangmasuk', 'BrgmskController@index');
    Route::get('/BarangmasukAdd', 'BrgmskController@create');
    Route::get('/Barangmasuk/{id}/edit', 'BrgmskController@edit');
    Route::patch('/Barangmasukedit', 'BrgmskController@editjum');
    Route::put('/Barangmasuk/{id}', 'BrgmskController@update');
    Route::put('/Barangmasukhapus/{id}', 'BrgmskController@destroy');
    Route::any('/Barangmasuk/data', 'BrgmskController@data');

    Route::get('/Barangkeluar', 'BrgkelController@index');
    // Route::get('/BarangkeluarAdd', 'BrgkelController@create');
    Route::get('/Barangkeluar/{id}/edit', 'BrgkelController@edit');
    Route::put('/Barangkeluar/{id}', 'BrgkelController@update');
    Route::put('/Barangkeluarhapus/{id}', 'BrgkelController@destroy');
    Route::any('/Barangkeluar/data', 'BrgkelController@data');

    Route::get('/Kasir', 'BrgkelController@kasir');

    Route::get('/Penjual', 'BrgkelController@create');


    Route::group(['prefix' => 'data'], function () {
        Route::resource('Kategori', 'KategoriController');
        Route::resource('Barang', 'BarangController');
        Route::resource('Supplier', 'SupplierController');
        Route::resource('Admin', 'AdminController');
        Route::resource('user', 'UserController'::class);
        Route::resource('Penjual', 'PenjualController');
        Route::resource('Barangmasuk', 'BrgmskController');
        Route::resource('Barangkeluar', 'BrgkelController');
    });
});

Route::group(['middleware' => ['auth', 'Checklevel:1,2']], function () {

    Route::get('/Userdetail/{id}', 'AdminController@show');
    Route::get('/User/{id}/edit', 'AdminController@edit');
    Route::put('/User/{id}', 'AdminController@update');

    Route::get('/UtamaAdmin', 'AdminController@admin');

    Route::get('/Laporan', 'LaporanController@index');
    Route::get('/Laporan/cetak_pdf',  'LaporanController@cetak_pdf')->name('print');

    Route::get('/TglLaporanPen', 'LaporanController@tgllpenjualan');
    Route::get('/LaporanPen/{tgl}', 'LaporanController@lpenjualan');
    Route::get('/LaporanPencetak/{tgl}',  'LaporanController@cetak2_pdf')->name('print');

    Route::get('/Laporanbm', 'LaporanController@lbm');
    Route::get('/Laporanbm/cetak_pdf',  'LaporanController@cetak3_pdf')->name('print');

    Route::group(['prefix' => 'data'], function () {
        Route::resource('Kategori', 'KategoriController');
        Route::resource('Barang', 'BarangController');
        Route::resource('Supplier', 'SupplierController');
        Route::resource('Admin', 'AdminController');
        Route::resource('user', 'UserController'::class);
        Route::resource('Penjual', 'PenjualController');
        Route::resource('Barangmasuk', 'BrgmskController');
        Route::resource('Barangkeluar', 'BrgkelController');
    });
});




// Route::get('/artikel', 'Articlecontroller@index');
// Route::get('/artikel/1', 'Articlecontroller@show');

// Route::get('user/login', 'userController@getLogin')->name('admin.login');
// Route::post('user/login', 'userController@postLogin');

// Route::get('/Admin', 'AdminController');


// Route::get('/PenjualAdd', 'PenjualController@create');
// Route::get('/Penjual/{id}/edit', 'PenjualController@edit');
// Route::put('/Penjual/{id}', 'PenjualController@update');

// Route::get('user/login', 'UserController@getLogin')->name('user.login');
// Route::post('user/login', 'UserController@postLogin');


// Route::get('/home', 'HomeController@index')->name('home');

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Kategori extends Model
{
    protected $fillable = ['namakat'];
    protected $primaryKey = 'Id_kategori';
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Kategori;
use Illuminate\Http\Request;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Kategori = Kategori::all();
        return view('Admin.Kategori.datakategori', compact('Kategori'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Admin.Kategori.add_kategori');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'namakat' => ['required']
        ]);
        Kategori::create($request->all());

        return redirect('Kategoridata')->with('success', 'Data berhasil di input');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */

    public function data(Request $request)
    {
        $orderBy = 'kategoris.Id_kategori';
        switch ($request->input('order.0.column')) {
            case "0":
                $orderBy = 'kategoris.Id_kategori';
                break;
            case "1":
                $orderBy = 'kategoris.namakat';
                break;
        }
        $data = Kategori::select([
            'kategoris.*'
        ]);

        if ($request->input('search.value') != null) {
            $data = $data->where(function ($q) use ($request) {
                $q->whereRaw('LOWER(kategoris.Id_kategori) like ? ', ['%' . strtolower($request->input('search.value')) . '%'])
                    ->orWhereRaw('LOWER(kategoris.namakat) like ? ', ['%' . strtolower($request->input('search.value')) . '%']);
            });
        }


        $recordsFiltered = $data->get()->count();
        if ($request->input('length') != -1) $data = $data->skip($request->input('start'))->take($request->input('length'));
        $data = $data->orderBy($orderBy, $request->input('order.0.dir'))->get();
        $recordsTotal = $data->count();
        return response()->json([
            'draw' => $request->input('draw'),
            'recordsTotal' => $recordsTotal,
            'recordsFiltered' => $recordsFiltered,
            'data' => $data
        ]);
    }

    public function show(Kategori $kategori)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Kategori = Kategori::find($id);
        return view('Admin.Kategori.editkategori', compact('Kategori'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Kategori = Kategori::find($id);
        $Kategori->namakat = $request->namakat;
        $Kategori->save();

        return redirect('/Kategoridata')->with('success', 'Data berhasil di ubah');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Kategori::find($id)->delete();
        return redirect('Kategoridata');
    }
}

resources/views/Admin/Kategori/add_kategori.blade.php
@extends('layouts.master')

@section('content') 
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Tambah Data Kategori
        <small>Data Kategori</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
        <li class="active">Tambah Kategori</li>
      </ol>
    </section>

    
    <section class="content">

    <form method="POST" action="{{url('data/Kategori')}}">
        @csrf
        <div class="card-body">
            <div class="form-group">
                <label>Nama Kategori</label>
                <input type="text" name="namakat" class="form-control" style="width: 300px">
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/Kategoridata/" class="btn btn-info btn-sm">Kembali</a>
            </div>

        </div>

    </form>


</section>
    

@endsection

resources/views/Admin/Kategori/datakategori.blade.php
@extends('layouts.master')

@section('content') 
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Kategori

      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
        <li class="active">Kategori</li>
      </ol>
    </section>

    
    <section class="content">

    @if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
    @endif

    <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <a href="/Kategori/" class="btn btn-info btn-sm">Tambah Kategori</a>
            </div>

            <div class="box-body">
                <table id="myTable" class="table table-bordered table-hover">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama</th>
                            <th>Action</th>
                        </tr>
                        {{-- <?php $i = 1; ?>
                        @foreach ($Kategori as $kat) --}}
                    </thead>
                    <tbody>
                        {{-- <tr>
                            <td>
                                {{ $i++ }}
                            </td>
                            <td>{{ $kat->namakat }}</td>
                            <td >
                                <div class="row">
                                    <div class="col-sm-2">
                                    <a href="/Kategori/{{$kat->Id_kategori}}/edit" class="btn btn-sm btn-success">edit</a>
                                    </div>
                                    <div class="col-sm-2">
                                    <form action="{{ route('Kategori.destroy', $kat->Id_kategori)}}" method="POST">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-sm btn-danger" onclick="return confirm('Apakah anda yakin ingin menghapus data {{$kat->namakat}}')">Delete</botton>
                                    </form>
                                    </div>
                                </div>
                            </td>
                        </tr> --}}
                    </tbody>
                {{-- @endforeach --}}
            </table>
            </div>
            </div>
        </div>
    </div>
    
    
</section>
    

@endsection

@section('js')


<script type="text/javascript">

    const table = $('#myTable').DataTable({
    "pageLength": 5,
    "lengthMenu": [[5, 10, 25, 50, 100, -1], [5, 10, 25, 50, 100, 'semua']],
    "bLengthChange": true,
    "bFilter": true,
    "bInfo": true,
    "processing":true,
    "bServerSide": true,
    "ajax":{
        url: "{{url('')}}/Kategoridata/data",
        type: "POST"
        },
        columnDefs: [
            { target: '_all', visible: true },
      {
        "targets": 0,
        "class":"text-nowrap",
        "render": function(data, type, row, meta){
          return row.Id_kategori;
        }
      },
      {
        "targets": 1,
        "class":"text-nowrap",
        "render": function(data, type, row, meta){ 
          return row.namakat;
        }
      },
      {
        "targets": 2,
        "sortable":false,
        "render": function(data, type, row, meta){
            let tampilan = ` 
            <div class="row">
                <div class="col-sm-2">
                <a href="/Kategori/${row.Id_kategori}/edit" class="btn btn-sm btn-success"><i class="fa fas fa-edit"></i></a>
                </div>
                <div class="col-sm-2">
                <form action="{{url('')}}/Kategorihapus/${row.Id_kategori}" method="POST">
                    @csrf
                    @method('DELETE')
                    <button class="btn btn-sm btn-danger" onclick="return confirm('Apakah anda yakin ingin menghapus data ${row.namakat}')"><i class="fa fas fa-trash"></i></botton>
                    </form>
                </div>
            </div>
                `;
          return tampilan;
        }
      }
        ]
    })

</script>

@endsection

resources/views/Admin/Kategori/editkategori.blade.php
@extends('layouts.master')

@section('content') 
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h1>
        Data Kategori
        <small>Data Kategori</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i>Home</a></li>
        <li class="active">Edit Kategori</li>
      </ol>
    </section>

    
    <section class="content">

    <form method="POST" action="/Kategori/{{$Kategori->Id_kategori}}">
        @csrf
        @method('PUT')

        <div class="card-body">
            <div class="form-group">
                <label>Nama Kategori</label>
                <input style="width: 300px" type="text" name="namakat" class="form-control" id="namakat" value="{{ old('namakat') ? old('namakat') : $Kategori->namakat }}">
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
                <a href="/Kategoridata/" class="btn btn-info btn-sm">Kembali</a>
            </div>

        </div>

    </form>


</section>
    
@endsection